{0}{45}
{52}{88}It's intermission time folks,
{90}{150}so hurry, hurry, hurry!
{157}{202}Step over to our refreshment center
{210}{294}with the most extravagant array of refreshment goodies
{300}{351}ever assembled under one roof!
{363}{430}Enjoy breathtaking mouth-watering goodies:
{435}{527}everything from a snack to a delicious full meal!
{538}{628}At our refreshment center you will find|a large variety of goodies
{629}{728}to satisfy your hunger, your thirst, or your sweet tooth.
{751}{913}So hurry, hurry, hurry!|Visit our refreshment center right now!
